import { assignmentFor } from "./operationalModel.js";
import { employeeDisplayName } from "./employeeMaster.js";

const DEFAULT_MESSAGES=[
  {id:"MSG-001",audienceType:"ALL",audienceId:"ALL",title:"Morning production briefing",body:"Ventilation work at Section 3 return airway remains in progress. Observe the temporary access controls and supervisor instructions.",priority:"NOTICE",authorRole:"System Administration",authorName:"MineMind Administrator",createdAt:"2026-09-08T05:45:00+02:00",expiresAt:"2026-09-09T18:00:00+02:00",active:true},
  {id:"MSG-002",audienceType:"TEAM",audienceId:"TEAM-SEC3-B",title:"Section 3 shift focus",body:"Prioritise housekeeping at Panel B access and confirm loose-rock re-inspection before entry.",priority:"IMPORTANT",authorRole:"Supervisor",authorName:"Mandla Khumalo",createdAt:"2026-09-08T06:05:00+02:00",expiresAt:"2026-09-09T18:00:00+02:00",active:true}
];
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function isCurrent(m){const t=Date.parse(m.expiresAt||"");return m.active!==false&&(!m.expiresAt||!Number.isFinite(t)||t>Date.now());}
export function visibleMessages(state,{role="employee",employee=null}={}){
  const items=Array.isArray(state.messages)&&state.messages.length?state.messages:DEFAULT_MESSAGES; const assignment=employee?assignmentFor(state,employee.id):null;
  return items.filter(m=>{if(!isCurrent(m))return false;if(m.audienceType==="ALL")return true;if(role!=="employee"||!employee)return false;if(m.audienceType==="EMPLOYEE")return m.audienceId===employee.id||m.audienceId===employee.employeeNumber;if(m.audienceType==="TEAM")return Boolean(assignment?.teamId&&m.audienceId===assignment.teamId);if(m.audienceType==="AREA")return Boolean(assignment?.areaId&&m.audienceId===assignment.areaId);return false;}).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));
}
function card(m){return `<article class="message-item ${m.priority==="IMPORTANT"?"important":""}"><div class="message-copy"><div class="message-title-row"><strong>${esc(m.title)}</strong><span>${esc(m.audienceType==="ALL"?"Mine-wide":m.audienceType==="TEAM"?"Team":m.audienceType)}</span></div><p>${esc(m.body)}</p><small>${esc(m.authorName||m.authorRole||"")} · ${new Date(m.createdAt).toLocaleString([],{dateStyle:"medium",timeStyle:"short"})}</small></div></article>`;}
function renderBoard(host,msgs){host.innerHTML=`<div class="message-board-head"><div><span class="eyebrow">Message board</span><strong>${msgs.length?`${msgs.length} current notice${msgs.length===1?"":"s"}`:"No current notices"}</strong></div>${msgs.length>3?`<button class="small secondary" data-message-toggle>View all</button>`:""}</div><div class="message-list">${msgs.map(card).join("")}</div>`;}
export function renderMessageBoards(state,employee=null){for(const role of ["employee","manager","executive","admin"]){const host=document.getElementById(`${role}MessageBoard`);if(!host)continue;renderBoard(host,visibleMessages(state,{role,employee:role==="employee"?employee:null}));}}
export function renderBrand(state){const b=state.mineIdentity||{};document.querySelectorAll(".mine-brand-logo").forEach(el=>{if(b.logoDataUrl){el.src=b.logoDataUrl;el.classList.remove("hidden");}else el.classList.add("hidden");});}
function canPublishTeamMessage(employee){return ["SUPERVISOR","BLASTING_SUPERVISOR"].includes(employee?.reportingRole);}
export function supervisorComposerHtml(state,employee){if(!canPublishTeamMessage(employee))return"";const a=assignmentFor(state,employee.id);if(!a?.teamId)return"";return `<details class="compact-disclosure supervisor-composer"><summary><div><strong>Team message</strong><span>Send a short notice to ${esc(a.teamName||a.teamId)}</span></div><span class="chevron">›</span></summary><form class="compact-form" data-supervisor-message data-employee-id="${esc(employee.id)}"><label>Title<input name="title" maxlength="80" required placeholder="Shift notice" /></label><label>Message<textarea name="body" maxlength="400" required rows="3" placeholder="What does the team need to know?"></textarea></label><label>Expiry<select name="expiry"><option value="8">End of shift (8h)</option><option value="24">24 hours</option><option value="72">3 days</option></select></label><button class="primary" type="submit">Send to team</button></form></details>`;}
export function bindCommunications({getState,setState,onStateChange}){
  document.addEventListener("click",e=>{const btn=e.target.closest("[data-message-toggle]");if(!btn)return;const board=btn.closest(".message-board");board?.classList.toggle("expanded");btn.textContent=board?.classList.contains("expanded")?"Show less":"View all";});
  document.addEventListener("submit",e=>{const form=e.target.closest("[data-supervisor-message]");if(!form)return;e.preventDefault();const state=getState();const employee=(state.employees||[]).find(x=>x.id===form.dataset.employeeId);if(!employee||!canPublishTeamMessage(employee))return;const a=assignmentFor(state,employee.id);if(!a?.teamId)return;const fd=new FormData(form),hours=Number(fd.get("expiry")||8),at=new Date().toISOString();state.messages=Array.isArray(state.messages)?state.messages:[];state.messages.unshift({id:`MSG-${Date.now()}`,audienceType:"TEAM",audienceId:a.teamId,title:String(fd.get("title")||"").trim(),body:String(fd.get("body")||"").trim(),priority:"NOTICE",authorRole:"Supervisor",authorName:employeeDisplayName(employee),authorEmployeeId:employee.id,createdAt:at,expiresAt:new Date(Date.now()+hours*3600000).toISOString(),active:true});state.auditTrail.push({type:"TEAM_MESSAGE_PUBLISHED",actorEmployeeId:employee.id,audienceType:"TEAM",audienceId:a.teamId,at});setState(state);onStateChange();form.reset();});
}
export function defaultMessages(){return DEFAULT_MESSAGES.map(x=>({...x}));}
