export const EMPLOYEES = Object.freeze([
  {
    id: "emp_104782",
    employeeNumber: "104782",
    pin: "1111",
    firstName: "Thabo",
    lastName: "Mokoena",
    jobTitle: "Engineering Artisan Mechanical UG",
    reportingRole: "FITTER",
    department: "Engineering",
    section: "Section 3",
    operation: "Demo Mine",
    supervisorEmployeeNo: "107199",
    employmentStatus: "ACTIVE",
    shiftGroup: "B",
    workLocation: "Underground",
    badgeId: "CARD-104782",
    mobileNumber: "",
    email: "",
    sourceSystem: "DEMO",
    sourceRecordId: "104782",
    effectiveFrom: "2026-01-01",
    effectiveTo: "",
    lastUpdatedAt: "2026-09-05T18:00:00+02:00"
  },
  {
    id: "emp_105310",
    employeeNumber: "105310",
    pin: "2222",
    firstName: "Sipho",
    lastName: "Dlamini",
    jobTitle: "Engineering Artisan Electrical UG",
    reportingRole: "ELECTRICIAN",
    department: "Engineering",
    section: "Section 3",
    operation: "Demo Mine",
    supervisorEmployeeNo: "107199",
    employmentStatus: "ACTIVE",
    shiftGroup: "B",
    workLocation: "Underground",
    badgeId: "CARD-105310",
    mobileNumber: "",
    email: "",
    sourceSystem: "DEMO",
    sourceRecordId: "105310",
    effectiveFrom: "2026-01-01",
    effectiveTo: "",
    lastUpdatedAt: "2026-09-05T18:00:00+02:00"
  },
  {
    id: "emp_106004",
    employeeNumber: "106004",
    pin: "3333",
    firstName: "Lerato",
    lastName: "Maseko",
    jobTitle: "Safety Officer UG",
    reportingRole: "SAFETY_OFFICER",
    department: "Safety",
    section: "Section 3",
    operation: "Demo Mine",
    supervisorEmployeeNo: "107199",
    employmentStatus: "ACTIVE",
    shiftGroup: "B",
    workLocation: "Underground",
    badgeId: "CARD-106004",
    mobileNumber: "",
    email: "",
    sourceSystem: "DEMO",
    sourceRecordId: "106004",
    effectiveFrom: "2026-01-01",
    effectiveTo: "",
    lastUpdatedAt: "2026-09-05T18:00:00+02:00"
  },
  {
    id: "emp_107199",
    employeeNumber: "107199",
    pin: "4444",
    firstName: "Mandla",
    lastName: "Khumalo",
    jobTitle: "Shiftboss Mining",
    reportingRole: "SUPERVISOR",
    department: "Production",
    section: "Section 3",
    operation: "Demo Mine",
    supervisorEmployeeNo: "",
    employmentStatus: "ACTIVE",
    shiftGroup: "B",
    workLocation: "Underground",
    badgeId: "CARD-107199",
    mobileNumber: "",
    email: "",
    sourceSystem: "DEMO",
    sourceRecordId: "107199",
    effectiveFrom: "2026-01-01",
    effectiveTo: "",
    lastUpdatedAt: "2026-09-05T18:00:00+02:00"
  },
  {
    id: "emp_108022",
    employeeNumber: "108022",
    pin: "5555",
    firstName: "Nandi",
    lastName: "Cele",
    jobTitle: "Rock Drill Operator",
    reportingRole: "OPERATOR",
    department: "Production",
    section: "Section 3",
    operation: "Demo Mine",
    supervisorEmployeeNo: "107199",
    employmentStatus: "ACTIVE",
    shiftGroup: "B",
    workLocation: "Underground",
    badgeId: "CARD-108022",
    mobileNumber: "",
    email: "",
    sourceSystem: "DEMO",
    sourceRecordId: "108022",
    effectiveFrom: "2026-01-01",
    effectiveTo: "",
    lastUpdatedAt: "2026-09-05T18:00:00+02:00"
  }
]);

export const DEMO_ATTENDANCE = Object.freeze([
  { employeeId: "emp_104782", clockedIn: true, clockInTime: "18:01" },
  { employeeId: "emp_105310", clockedIn: true, clockInTime: "17:58" },
  { employeeId: "emp_106004", clockedIn: true, clockInTime: "18:03" },
  { employeeId: "emp_107199", clockedIn: true, clockInTime: "17:49" },
  { employeeId: "emp_108022", clockedIn: true, clockInTime: "18:05" }
]);

export const DEMO_INITIAL_SUBMISSIONS = Object.freeze([
  {
    employeeId: "emp_104782",
    shiftId: "NS-20260905",
    reportingRole: "FITTER",
    status: "complete",
    completedAt: "2026-09-05T18:47:00+02:00",
    answers: { equipmentWorkedOn: "CV-04", equipmentConcern: "yes", equipmentCondition: "Abnormal vibration near drive pulley", outstandingWork: "Inspect bearing alignment on next shift", handoverNote: "Monitor CV-04 before full load" }
  },
  {
    employeeId: "emp_106004",
    shiftId: "NS-20260905",
    reportingRole: "SAFETY_OFFICER",
    status: "complete",
    completedAt: "2026-09-05T18:42:00+02:00",
    answers: { hazardsObserved: "yes", hazardDetails: "Loose rock observed near Panel B access", incidentOrNearMiss: "no", correctiveAction: "Area barricaded and supervisor informed", outstandingSafety: "Re-inspection required before next entry" }
  }
]);
