
let bindings=null;
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function tone(level){return level==="GOOD"?"good":level==="CRITICAL"?"critical":"attention";}
function label(level){return level==="GOOD"?"Green":level==="CRITICAL"?"Red":"Yellow";}
function statusState(state){return state?.operationalStatus||{production:{level:"ATTENTION",reason:"Status not configured.",updatedAt:null,updatedBy:"—"},safety:{level:"ATTENTION",reason:"Status not configured.",updatedAt:null,updatedBy:"—"}};}
function timeLabel(v){if(!v)return"—";try{return new Date(v).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"});}catch{return"—";}}

export function renderLoginMineSignals(state){const host=document.getElementById("loginMineSignals");if(!host)return;const s=statusState(state);host.innerHTML=`<div class="login-signal ${tone(s.safety.level)}"><span class="status-dot"></span><span>Safety</span><strong>${label(s.safety.level)}</strong></div><div class="login-signal ${tone(s.production.level)}"><span class="status-dot"></span><span>Operational Performance</span><strong>${label(s.production.level)}</strong></div>`;}
export function renderOperationalStatusBars(state){const s=statusState(state);for(const view of document.querySelectorAll(".view")){let host=view.querySelector(".operational-status-strip");if(!host){host=document.createElement("div");host.className="operational-status-strip";const header=view.querySelector(".view-header");if(header)header.insertAdjacentElement("afterend",host);else view.prepend(host);}host.innerHTML=`<button class="mine-status ${tone(s.production.level)}" data-status-detail="production" type="button"><span class="status-dot"></span><span><small>Operational Performance</small><strong>${label(s.production.level)}</strong></span></button><button class="mine-status ${tone(s.safety.level)}" data-status-detail="safety" type="button"><span class="status-dot"></span><span><small>Safety Status</small><strong>${label(s.safety.level)}</strong></span></button><div class="status-context">Mine-wide · governed history · tap for reason</div>`;host.querySelectorAll("[data-status-detail]").forEach(button=>button.addEventListener("click",()=>{const key=button.dataset.statusDetail,item=s[key];alert(`${key==="production"?"Operational Performance":"Safety"}: ${label(item.level)}\n\n${item.reason}\n\nUpdated ${timeLabel(item.updatedAt)} by ${item.updatedBy}`);}));}}

export function renderStatusAdminControl(state){const admin=document.getElementById("adminWorkspace");if(!admin)return;const s=statusState(state);let host=document.getElementById("operationalStatusAdmin");if(!host){host=document.createElement("section");host.id="operationalStatusAdmin";host.className="card operational-status-admin section-block";admin.prepend(host);}host.innerHTML=`<div class="section-title"><div><div class="eyebrow">Operational status</div><h3>Safety & operational performance</h3></div><span class="badge">Governed history</span></div><p class="muted">Mine-wide indicators are administrator-set. Every update is retained in the main application state and audit trail.</p><form id="statusAdminForm" class="status-admin-grid">${["production","safety"].map(key=>{const item=s[key],title=key==="production"?"Operational Performance":"Safety";return `<fieldset><legend>${title}</legend><label>Status<select name="${key}Level"><option value="GOOD" ${item.level==="GOOD"?"selected":""}>Green · Good</option><option value="ATTENTION" ${item.level==="ATTENTION"?"selected":""}>Yellow · Attention</option><option value="CRITICAL" ${item.level==="CRITICAL"?"selected":""}>Red · Critical</option></select></label><label>Reason<textarea name="${key}Reason" required>${esc(item.reason||"")}</textarea></label></fieldset>`;}).join("")}<div class="status-admin-actions"><label>Updated by<input name="updatedBy" value="System Administrator" required /></label><button class="primary" type="submit">Update mine status</button></div></form><div id="statusAdminMessage"></div><details class="compact-disclosure"><summary><div><strong>Status history</strong><span>${(state.operationalStatusHistory||[]).length} recorded changes</span></div><span class="chevron">›</span></summary><div class="admin-list">${[...(state.operationalStatusHistory||[])].reverse().slice(0,10).map(x=>`<div class="admin-row"><div class="admin-row-copy"><strong>${esc(x.statusType)} · ${esc(x.level)}</strong><span>${esc(x.reason)} · ${new Date(x.at).toLocaleString()} · ${esc(x.actor)}</span></div></div>`).join("")}</div></details>`;}

export function bindOperationalStatus(args){bindings=args;document.addEventListener("submit",e=>{if(e.target?.id!=="statusAdminForm")return;e.preventDefault();const state=bindings.getState(),data=new FormData(e.target),now=new Date().toISOString(),actor=String(data.get("updatedBy")||"System Administrator");state.operationalStatus=state.operationalStatus||{};state.operationalStatusHistory=Array.isArray(state.operationalStatusHistory)?state.operationalStatusHistory:[];for(const key of ["production","safety"]){const next={level:String(data.get(`${key}Level`)||"ATTENTION"),reason:String(data.get(`${key}Reason`)||"").trim(),updatedAt:now,updatedBy:actor};state.operationalStatus[key]=next;state.operationalStatusHistory.push({statusEventId:`STS-${key.toUpperCase()}-${Date.now()}-${Math.random().toString(36).slice(2,5)}`,statusType:key,level:next.level,reason:next.reason,at:now,actor});}state.auditTrail.push({type:"OPERATIONAL_STATUS_UPDATED",actor,at:now});bindings.setState(state);bindings.onStateChange();const msg=document.getElementById("statusAdminMessage");if(msg)msg.innerHTML='<div class="status-box success">Mine status updated and retained in governed history.</div>';});}

